name: Keep Render Bot Alive

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install deps
        run: pip install requests

      - name: Ping Render
        run: python -c "import requests; print(requests.get('https://all-bot-9j5c.onrender.com').status_code)"
